Store and Components
AymenBida/magic-books pull request #2
Opened 2021-06-03 17:33 UTC by AymenBida

In this milestone I did: 

- Create different components for the different parts of the app (book, booksList, booksForm)
- Create a Redux store and connected it to the booksList component

2021-06-03 18:56 UTC, arslanbisharat reviewed
I cannot review the project https://github.com/AymenBida/magic-books/pull/2/ at this moment as I have urgent work to do. Please request another review.

2021-06-04 06:25 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this milestone.
You managed to fulfill most requirements for this milestone. Well done!
### Changes 🙅🏿 🙅🏿 🙅🏿 
- Remove comments from the codebase
- Move files to the right folders. Check my comments.

### Martin Afani
#### Slack: whiz25

2021-06-04 06:25 UTC, afanimartin commented on src/containers/App.js
> +import BooksList from '../components/BooksList';
- Move this component to `src/components`

2021-06-04 06:25 UTC, afanimartin commented on src/components/BooksList.js
> +
- Move this component to `src/containers` where it rightly belongs

2021-06-04 06:25 UTC, afanimartin commented on src/components/BooksForm.js
> +];
- Move this to `src/containers`

2021-06-04 06:25 UTC, afanimartin commented on src/redux/actions/index.js
> +// const REMOVE_BOOK = 'REMOVE_BOOK';
- Remove this comment

2021-06-04 11:13 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @AymenBida**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-06-04 11:39 UTC, closed without merging