Create and Remove
AymenBida/magic-books pull request #3
Opened 2021-06-03 21:37 UTC by AymenBida

In this milestone I did: 

- Implement the createBook action 
- Implement the removeBook action

2021-06-04 13:32 UTC, Berabjesus requested changes
# Status: REQUIRED CHANGES :warning: :construction: 
Hey @AymenBida excellent job on this milestone. You have written a clean code that does the job.
### However, there is one minor change you need to make.

- [ ] `BookForm` component should implement `handleSubmit` and attaches it to **form's** `onSubmit` event [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/HandleSubmit.png). Although your code does the job well its best to handle form submission in a different way since its handling a submit action, not a click action. Check the inline comment below.

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-06-04 13:32 UTC, Berabjesus commented on src/containers/BooksForm.js
> +    </form>
- [ ] Lets make the button type `submit` `<button type="button" onClick={handleSubmit}>Submit</button>` and add ` <form onSubmit={handleSubmit}>` to the form.

2021-06-04 13:32 UTC, Berabjesus commented on src/containers/BooksForm.js
> +  };
- [ ] Add `event.preventDefault();` before dispatch to prevent page refresh after the submit button is clicked.

2021-06-06 05:35 UTC, afanimartin approved these changes
## Approved ✅ ✅ ✅ 
Nice work making the requested change. Merge and proceed to the next milestone.


### Martin Afani
#### Slack: whiz25

2021-06-07 09:31 UTC, closed without merging